# CONVENTION MODEL FIELDS ALIASES
REFERENCE_ALIAS = "Reference"
TITRE_ALIAS = "Title"
PORTEUR_ALIAS = "Porteur"
STRUCTURE_PORTEUR_ALIAS = "StructurePorteur"
RESPONSABLE_PORTEUR_ALIAS = "ResponsablePorteur"
REFERENT_DAJI_ALIAS = "ReferentDAJI"
PARTENAIRE_ALIAS = "Partenaire"
DESCRIPTION_ALIAS = "DescriptionConvention"
ORIGINE_CONVENTION_ALIAS = "OrigineConvention"
MONTANT_CONVENTION_ALIAS = "MontantConvention"
TYPE_CONVENTION_ALIAS = "TypeConvention"
SOUS_TYPE_CONVENTION_ALIAS = "SousType"
DATE_DEMARRAGE_ALIAS = "DateDemarrage"
TERME_CONVENTION_ALIAS = "TermeConvention"
ETAPE_ALIAS = "Etape"

# OTHERS
CONFIRMED_ACTIVITY_ALIAS = "ConfirmedActivities"
